# mssql server express image
FROM microsoft/windowsservercore

# maintainer for image metadata
MAINTAINER Sergiy Melnykov

# Set one or more individual labels
LABEL com.cqg.gateway.version="5.05.00000"
LABEL vendor="CQG Inc"
LABEL com.cqg.gatcom.cqg.gateway.version.is-production="NO"

# set environment variables

ENV sql_2008_ISO_file "SW_DVD5_SQL_Svr_Standard_Edtn_2008_English_MLF_X14-89155.ISO"
ENV win64_ISO_file "en_windows_server_2016_x64_dvd_9327751.iso"
ENV sa_password _
ENV attach_dbs "[]"
ENV ACCEPT_EULA _cd .

EXPOSE 1434

# make install files accessible
#COPY ./install.bat /
WORKDIR /

# Uses dism.exe to install the NetFX3.
RUN   powershell -Command Get-DiskImage -ImagePath "./ISO/%win64_ISO_file%" \
      && Install-WindowsFeature NET-Framework-Features / -Source "E`\winsxs"
      #RUN dism.exe /online /enable-feature /all /featurename:NetFX3 /All /NoRestart
RUN dism.exe /online /enable-feature /all /featurename:NetFX3 /All /NoRestart
#RUN powershell -Command "Install-WindowsFeature NET-Framework-Features"
#RUN powershell -Command "Install-WindowsFeature Web-Asp-Net"
# download and install Microsoft SQL 2008 standard Edition in one step
# RUN powershell -Command (New-Object System.Net.WebClient).DownloadFile('%sql_2008_download_url%', 'sqlexpress.exe') && /sqlexpress.exe /qs /x:setup && /setup/setup.exe /q /ACTION=Install /INSTANCENAME=SQLEXPRESS /FEATURES=SQLEngine /UPDATEENABLED=0 /SQLSVCACCOUNT="NT AUTHORITY\System" /SQLSYSADMINACCOUNTS="BUILTIN\ADMINISTRATORS" /TCPENABLED=1 /NPENABLED=0 /IACCEPTSQLSERVERLICENSETERMS && del /F /Q sqlexpress.exe && rd /q /s setup

RUN   powershell -Command Get-DiskImage -ImagePath "%sql_2008_ISO_file%" \
      && install.bat E:
RUN powershell -Command \
        set-strictmode -version latest ; \
        stop-service MSSQL`$SQLEXPRESS ; \
        set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql13.SQLEXPRESS\mssqlserver\supersocketnetlib\tcp\ipall' -name tcpdynamicports -value '' ; \
        set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql13.SQLEXPRESS\mssqlserver\supersocketnetlib\tcp\ipall' -name tcpport -value 1433 ; \
        set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql13.SQLEXPRESS\mssqlserver\' -name LoginMode -value 2 ;

CMD powershell ./start -sa_password %sa_password% -ACCEPT_EULA %ACCEPT_EULA% -attach_dbs \"%attach_dbs%\" -Verbose
